name: execut
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.2.5

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0 
  mysql_client: ^0.0.27
  shelf: ^1.4.1
  shelf_plus: ^1.0.2
  shelf_router: ^1.1.4
  json_annotation: ^4.9.0
  uuid: ^4.4.0


dev_dependencies:
  lints: ^2.1.0
  test: ^1.24.0
  build_runner: ^2.4.9
  json_serializable: ^6.8.0
