name: execut
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.2.5

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0 
  mysql_client: ^0.0.27
  shelf: ^1.4.1
  shelf_router: ^1.1.4

dev_dependencies:
  dotenv: ^4.2.0
  lints: ^2.1.0
  test: ^1.24.0
